'use strict';
// Service definitions are factual references. Recommendations are Winwise's
// conditional editorial judgments for general-purpose Windows 11 PCs.
const SOURCES = {
  stopService:{title:'Microsoft: Stop-Service and dependent services',url:'https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/stop-service',note:'The script uses Stop-Service without -Force to refuse stopping a service with running dependents.'},
  restore:{"title": "Microsoft: System Restore", "url": "https://support.microsoft.com/en-us/windows/experience/backup-recovery/system-restore", "note": "What restore points cover and how to apply one from Windows Recovery Environment."},
  protection:{"title": "Microsoft: System Protection", "url": "https://support.microsoft.com/en-us/windows/experience/backup-recovery/system-protection", "note": "Enable System Protection and create a restore point before changing Windows."},
  recovery:{"title": "Microsoft: Windows Recovery Environment", "url": "https://support.microsoft.com/en-us/windows/experience/backup-recovery/windows-recovery-environment", "note": "Shift + Restart, Automatic Repair, and alternative recovery tools."},
  settingsLinks:{"title": "Microsoft: Launch Windows Settings", "url": "https://learn.microsoft.com/en-us/windows/apps/develop/launch/launch-settings", "note": "Supported Settings links. Page availability and labels depend on Windows version and edition."},
  audit:{"title": "Microsoft: Audit-failure shutdown policy", "url": "https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/security-policy-settings/audit-shut-down-system-immediately-if-unable-to-log-security-audits", "note": "Windows 11 can halt when security auditing fails if this policy is enabled; this is not the default."},
  cachedLogon:{"title": "Microsoft: Cached domain logon", "url": "https://learn.microsoft.com/en-us/troubleshoot/windows-server/user-profiles-and-logon/cached-domain-logon-information", "note": "Why domain sign-in can require network access when cached logon is unavailable."},
  rpcRecovery:{"title": "Microsoft: Restore required RPC services", "url": "https://learn.microsoft.com/en-us/troubleshoot/windows-client/installing-updates-features-roles/troubleshoot-windows-update-error-0x800706d9", "note": "RPC and Endpoint Mapper dependencies; recovery guidance includes systems that cannot start."},

  mdm:{title:'Microsoft: Device management and WAP Push Routing',url:'https://learn.microsoft.com/en-us/troubleshoot/mem/intune/device-management/cannot-sync-windows-10-devices',note:'Why disabling dmwappushservice can prevent Intune synchronization.'},
  input:{title:'Microsoft: Text input service and IME problems',url:'https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/troubleshoot-ime-common-issues',note:'Input-method failures when text-input services are disabled, and service-name differences across Windows builds.'},
  system:{title:'Microsoft: Windows service reference',url:'https://learn.microsoft.com/en-us/windows/iot/iot-enterprise/optimize/services',note:'Service definitions. Microsoft’s disable recommendations on this page target fixed-purpose IoT Enterprise devices, not every personal PC.'},
  user:{title:'Microsoft: Per-user services in Windows',url:'https://learn.microsoft.com/en-us/windows/application-management/per-user-services-in-windows',note:'Session-specific services, their dependencies, and version differences.'},
  diagnostic:{title:'Microsoft: Configure Windows diagnostic data',url:'https://learn.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization',note:'Diagnostic components and organization policies.'},
  privacy:{title:'Microsoft: Diagnostics, feedback, and privacy',url:'https://support.microsoft.com/en-us/windows/privacy/diagnostics-feedback-and-privacy-in-windows',note:'Required and optional diagnostic data and their controls.'},
  search:{title:'Microsoft: Search indexing in Windows',url:'https://support.microsoft.com/en-us/windows/experience/performance-optimization/search-indexing-in-windows',note:'Indexing scope, resource tradeoffs, and applications that use the index.'},
  location:{title:'Microsoft: Location service and privacy',url:'https://support.microsoft.com/en-us/windows/privacy/windows-location-service-and-privacy',note:'Location permissions and the limits of turning location off.'},
  delivery:{title:'Microsoft: Delivery Optimization in Windows',url:'https://support.microsoft.com/en-us/windows/deployment/updates-lifecycle/delivery-optimization-in-windows',note:'Peer download controls for updates.'},
  errors:{title:'Microsoft: Windows Error Reporting guidance',url:'https://learn.microsoft.com/en-us/troubleshoot/windows-client/system-management-components/windows-error-reporting-diagnostics-enablement-guidance',note:'Crash reporting and policy controls.'},
  network:{title:'Microsoft: Network service overview',url:'https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements',note:'Network service roles. Server configuration advice is not a desktop disable preset.'},
  bluetooth:{title:'Microsoft: Bluetooth driver stack',url:'https://learn.microsoft.com/en-us/windows-hardware/drivers/bluetooth/bluetooth-driver-stack',note:'Bluetooth support and device connections.'},
  print:{title:'Microsoft: Print Spooler service',url:'https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-prsod/7262f540-dd18-46a3-b645-8ea9b59753dc',note:'The Windows printing service and its client/server responsibilities.'},
  registry:{title:'Microsoft: Remote Registry protocol',url:'https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rrp/0fa3191d-bb79-490a-81bd-54c2601b7a78',note:'Remote registry access.'},
  firewall:{title:'Microsoft: Manage Windows Firewall',url:'https://learn.microsoft.com/en-us/windows/security/operating-system-security/network-security/windows-firewall/configure-with-command-line',note:'Supported firewall configuration instead of stopping its service.'},
  vss:{title:'Microsoft: Volume Shadow Copy Service',url:'https://learn.microsoft.com/en-us/windows/win32/vss/the-volume-shadow-copy-service',note:'Volume snapshots and their use by backup applications.'},
  hyperv:{title:'Microsoft: Hyper-V integration services',url:'https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/integration-services',note:'Windows 11 guest services and their impact inside a VM.'},
  startup:{title:'Microsoft: Configure startup applications',url:'https://support.microsoft.com/en-us/windows/experience/startup-boot/configure-startup-applications-in-windows',note:'An alternative place to investigate background load.'},
  powershell:{title:'Microsoft: Set-Service',url:'https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-service',note:'Service configuration commands and dependencies.'}
};
function service(id,name,category,status,summary,tradeoff,advice,source='system',extra={}){return {id,name,category,status,summary,tradeoff,advice,source,...extra};}
const SERVICES = [
  service("DiagTrack","Connected User Experiences and Telemetry","privacy","settings","Start by limiting optional diagnostic data.","Diagnostic collection handled by this service stops. Windows Error Reporting and individual apps have separate controls.","Turn off optional diagnostic data in Settings → Privacy & security → Diagnostics & feedback first. Disabling the service is also available as an opt-in in the script builder.","diagnostic",{"script": true, "description": "Collects and sends Windows diagnostic events and logs according to your diagnostic data settings.", "aliases": ["Diagnostics Tracking Service", "Diagnostics Tracking", "Diagnostic Tracking Service"]}),
  service("dmwappushservice","WAP Push Message Routing Service","privacy","keep","Keep available for Intune and device management.","Disabling it can prevent an enrolled PC from synchronizing with Microsoft Intune and receiving device-management actions.","Leave it at its existing default, particularly on a PC enrolled in Microsoft Intune or another device-management system.","mdm",{"description": "Routes device-management push messages. Microsoft Intune uses this service for device synchronization.", "availability": "Its full display name may include “Device Management Wireless Application Protocol.” Availability and configuration vary by build and management setup."}),
  service("WerSvc","Windows Error Reporting Service","privacy","keep","Review report settings before disabling diagnostics.","Crash reports, diagnostic logs, and suggested fixes may become unavailable, making recurring failures harder to investigate.","Use Windows Error Reporting policies where supported to control report submission. Reports follow the applicable consent and policy settings.","errors",{"description": "Collects information about crashes and unresponsive applications for troubleshooting and error reports.", "recommendation": "Use reporting policy"}),
  service("RemoteRegistry","Remote Registry","privacy","conditional","Can disable if remote registry administration is unused.","Remote registry management tools stop working with this PC. Local Registry Editor remains available.","On your own PC, disable it if no remote administration tool needs it. Keep it when required by your IT team or management software. If it is already disabled, leave it alone.","registry",{"script": true, "description": "Lets authorized remote administration tools read and change the Windows registry, subject to account permissions and device configuration."}),
  service("SysMain","SysMain (Superfetch)","performance","conditional","Consider a change when SysMain causes persistent disk or CPU activity.","Preloading stops, so frequently used applications may take longer to open.","Keep the default unless persistent background activity has been traced to this service. If you disable it and app launches become slower, restore the previous setting.","system",{"script": true, "description": "Learns usage patterns and preloads application data into memory to help frequently used apps launch faster.", "recommendation": "Only for troubleshooting"}),
  service("WSearch","Windows Search","performance","settings","Try fewer indexed locations before turning it off.","File Explorer and apps that use the Windows index, including classic Outlook, may return slower or incomplete search results.","Choose Classic indexing or exclude busy folders in Settings → Privacy & security → Search or Searching Windows. Disable only if you accept the effect on all apps using the index.","search",{"script": true, "description": "Builds and updates a local index so Windows and compatible apps can quickly find files, properties, and file contents."}),
  service("Spooler","Print Spooler","optional","conditional","Can disable if you never print, including to PDF.","Local printers, shared printers, and virtual printing such as Microsoft Print to PDF can stop working.","Keep it for any print workflow, even without a physical printer. If you never print, review its dependencies and disable it with a backup of the original settings.","print",{"script": true, "description": "Queues print jobs and connects applications to local, network, and virtual printers."}),
  service("PrintDeviceConfigurationService","Print Device Configuration Service","optional","conditional","Can disable only if you never print or add a printer.","Adding or configuring printers may fail.","Keep it if you print or add printers. The script skips this service if it is not installed.","print",{"script": true, "description": "Handles print-device configuration.", "availability": "May be absent depending on the Windows build and installed printing components."}),
  service("Fax","Fax","optional","conditional","Can disable when Windows fax features are unused.","Sending or receiving faxes through Windows becomes unavailable. Other fax software may have different requirements.","Disable if you do not use Windows faxing. If the service is absent or already disabled, no action is needed; the script skips it.","network",{"script": true, "description": "Provides Windows fax sending and receiving when the optional fax components are installed.", "availability": "Optional feature. The Fax service may not exist on your Windows 11 installation."}),
  service("TabletInputService","Touch Keyboard and Handwriting Panel Service","optional","keep","Keep input services available, even without touch.","On-screen typing, handwriting, and input-method functions can stop working.","Leave input services at their existing defaults, including on PCs with a physical keyboard.","input",{"description": "Supports touch-keyboard and handwriting input. Related text-input services also support input method editors (IMEs).", "aliases": ["TextInputManagementService", "Text Input Management Service", "inking", "stylus", "IME"], "availability": "The name differs across Windows builds. Newer versions use Text Input Management Service; search your local service list for the exact name."}),
  service("wisvc","Windows Insider Service","optional","conditional","Can disable if this PC is not an Insider device.","Windows Insider Program functionality can stop working. Disabling the service does not convert an installed preview build into a stable release.","Consider disabling only on a stable, unenrolled PC. If you already receive preview builds, use Settings → Windows Update → Windows Insider Program to follow the supported opt-out process.","system",{"script": true, "description": "Provides supporting infrastructure for the Windows Insider Program and its preview-build experience."}),
  service("TermService","Remote Desktop Services","optional","conditional","If this PC never hosts Remote Desktop.","Incoming Remote Desktop sessions and related remote-session features become unavailable. This can disconnect your current session.","Prefer turning Remote Desktop off in Settings → System. If disabling services, run locally at the PC and keep them if any remote-session feature is needed. Host availability depends on edition.","network",{"script": true, "description": "Lets this PC host Remote Desktop sessions so another computer can connect to it."}),
  service("lfsvc","Geolocation Service","privacy","settings","Review location permissions first.","Location-aware apps, automatic location features, and Find my device can lose functionality. Apps may still infer location from an IP address.","Use Settings → Privacy & security → Location to manage the service and app permissions. Check Find my device before switching location off.","location",{"description": "Provides location information to Windows features and apps that have permission to use it."}),
  service("DoSvc","Delivery Optimization","performance","settings","Limit peer downloads in Settings.","Disabling the service can interfere with content and update delivery. Turning off peer sharing still allows direct downloads.","In Settings → Windows Update → Advanced options → Delivery Optimization, turn off downloads from other devices or restrict their scope. Keep the service available.","delivery",{"description": "Downloads Windows updates and other Microsoft content, with optional sharing between PCs."}),
  service("bthserv","Bluetooth Support Service","optional","conditional","If you use no Bluetooth devices.","Bluetooth pairing and connected peripherals can fail. This includes keyboards, mice, controllers, headsets, and some accessibility devices.","Use a wired keyboard and mouse before changing this service. Keep it if you might reconnect a Bluetooth device. Turning Bluetooth off in Settings is a simpler alternative.","bluetooth",{"script": true, "description": "Supports Bluetooth device discovery and pairing."}),
  service("BTAGService","Bluetooth Audio Gateway Service","optional","conditional","If Bluetooth headset calling is unused.","Hands-free headset audio, including the microphone used for calls, may stop working.","Keep it if you use a Bluetooth headset for voice or video calls.","system",{"script": true, "description": "Supports the Bluetooth hands-free audio connection used for headset calls."}),
  service("BthAvctpSvc","AVCTP Service","optional","conditional","If Bluetooth media controls are unused.","Playback controls on Bluetooth audio devices may stop working.","Keep it for Bluetooth audio devices that use remote playback controls.","system",{"script": true, "description": "Handles Bluetooth audio and video remote-control commands, such as playback controls."}),
  service("RetailDemo","Retail Demo Service","optional","conditional","If this is not a retail demonstration PC.","Retail demonstrations become unavailable.","Leave disabled if already off.","system",{"script": true, "description": "Supports the demonstration mode used on retail display PCs."}),
  service("UmRdpService","Remote Desktop Services UserMode Port Redirector","optional","conditional","If redirected Remote Desktop devices are unused.","Drive, printer, and other device redirection in remote sessions may fail.","Review together with Remote Desktop Services. Disable only from a local session when you do not host or need these features.","network",{"script": true, "description": "Redirects client printers, drives, and supported devices into a Remote Desktop session."}),
  service("SessionEnv","Remote Desktop Configuration","optional","conditional","If Remote Desktop session setup is unused.","Remote Desktop sessions may fail to initialize or use their configured settings.","Review with Remote Desktop Services; keep it for remote-session workflows.","network",{"script": true, "description": "Sets up and maintains the configuration needed for Remote Desktop sessions."}),
  service("SSDPSRV","SSDP Discovery","optional","conditional","If network media discovery is unused.","UPnP discovery may stop finding network devices such as media receivers.","Keep it for devices or media apps that rely on UPnP discovery. Review UPnP Device Host alongside it.","network",{"script": true, "description": "Discovers network devices that advertise through SSDP, including UPnP media devices."}),
  service("upnphost","UPnP Device Host","optional","conditional","If you do not host UPnP devices.","UPnP devices hosted on this PC become unavailable to other devices.","Keep it if your media-sharing or device software uses UPnP hosting.","system",{"script": true, "description": "Allows UPnP devices to be hosted on this PC."}),
  service("fdPHost","Function Discovery Provider Host","optional","conditional","If automatic network discovery is unused.","Apps using these providers may stop discovering network devices and shared resources.","Keep it if you use automatic discovery of network printers, media devices, or shared resources.","system",{"script": true, "description": "Hosts the SSDP and WS-Discovery providers that apps use to find network devices and resources."}),
  service("FDResPub","Function Discovery Resource Publication","optional","conditional","If other PCs do not need to discover this PC.","Other computers may no longer find this PC or its shared resources through network discovery.","Keep it if you want this PC and its shares to appear in network browsing.","system",{"script": true, "description": "Advertises this PC and its shared resources so other computers can discover them on the network."}),
  service("WMPNetworkSvc","Windows Media Player Network Sharing Service","optional","conditional","If legacy media-library sharing is unused.","Other devices lose access to the shared media library. This service depends on installed media features.","Disable only if no device streams from this PC through the legacy Windows Media Player sharing feature.","network",{"script": true, "description": "Shares the legacy Windows Media Player library with compatible network devices."}),
  service("CDPSvc","Connected Devices Platform Service","privacy","settings","Review connected-device features first.","Windows features that rely on the Connected Devices Platform may stop connecting to other devices.","Turn off unused features, such as Nearby sharing, in their own settings. Keep the service available for any connected-device features you still use.","system",{"description": "Supports Windows features that connect and communicate with other devices."}),
  service("CDPUserSvc","Connected Devices Platform User Service","privacy","settings","If nearby or cross-device experiences are unused.","Connected-device features in your user session may stop working.","Turn off unused sharing features in Settings rather than disabling the per-user service template.","user",{"perUser": true, "description": "Provides connected-device support within the signed-in user’s session."}),
  service("cbdhsvc","Clipboard User Service","privacy","settings","Review clipboard history and cloud sync.","Clipboard history or synchronization may fail.","Use Settings → System → Clipboard.","user",{"perUser": true, "description": "Supports clipboard history and clipboard synchronization across devices."}),
  service("OneSyncSvc","Sync Host","privacy","keep","Review account synchronization.","Apps that use this service may stop synchronizing mail, calendars, and contacts.","Use the account or synchronization controls in the affected app.","user",{"perUser": true, "recommendation": "Use account sync controls", "description": "Synchronizes mail, calendars, contacts, and other user data for apps that use this Windows service."}),
  service("BcastDVRUserService","Game DVR and Broadcast User Service","performance","settings","If background game recording is unused.","Game capture becomes unavailable.","Use Settings → Gaming → Captures.","user",{"perUser": true, "description": "Supports Windows game recording and broadcasting features."}),
  service("CaptureService","OneCore Capture Service","optional","keep","Keep available for screen capture.","Screen capture may fail in apps that use this Windows API.","Keep it available for screen capture and screen-sharing apps.","user",{"perUser": true, "description": "Supports screen capture for apps that use the Windows.Graphics.Capture API."}),
  service("BluetoothUserService","Bluetooth User Support Service","optional","settings","Review together with your Bluetooth devices.","Per-user Bluetooth features may fail.","Use Bluetooth settings first.","user",{"perUser": true, "description": "Supports Bluetooth functions specific to the signed-in user’s session."}),
  service("PimIndexMaintenanceSvc","Contact Data","optional","keep","Keep available for contact search.","Contacts may disappear from search.","Leave the default configuration.","user",{"perUser": true, "description": "Indexes contact data so supported apps can search it quickly."}),
  service("UserDataSvc","User Data Access","optional","keep","Keep available for dependent apps.","Apps that use this service may lose access to contacts, calendars, and other shared user data.","Leave the default configuration.","user",{"perUser": true, "description": "Gives supported apps access to structured user data, including contacts and calendars."}),
  service("UnistoreSvc","User Data Storage","optional","keep","Keep available for dependent apps.","Apps that use this store may be unable to read or save contacts, calendars, and related data.","Leave the default configuration.","user",{"perUser": true, "description": "Stores structured user data, including contacts and calendars, for supported apps."}),
  service("PrintWorkflowUserSvc","Print Workflow","optional","keep","Keep available for print applications.","Print-workflow apps may be unable to prepare or customize print jobs.","Leave available when printing.","user",{"perUser": true, "description": "Supports print-workflow applications within the signed-in user’s session."}),
  service("WpnUserService","Windows Push Notifications User Service","essential","keep","Keep notifications available.","Local and push alerts may fail.","Disable unwanted app notifications in Settings.","user",{"perUser": true, "description": "Delivers local and push notifications to the signed-in user."}),
  service("vmicheartbeat","Hyper-V Heartbeat Service","optional","keep","Keep if Windows runs inside a VM.","The host loses guest-health reporting.","On physical PCs, leave dormant integration services alone.","hyperv",{"description": "Reports to the Hyper-V host that the guest operating system is running."}),
  service("vmicshutdown","Hyper-V Guest Shutdown Service","optional","keep","Keep if Windows runs inside a VM.","Host-initiated graceful shutdown is unavailable.","Avoid replacing a graceful shutdown with a forced power-off.","hyperv",{"description": "Lets the Hyper-V host request a normal shutdown of this guest operating system."}),
  service("vmictimesync","Hyper-V Time Synchronization Service","optional","keep","Keep if Windows runs inside a VM.","Host-to-guest time synchronization stops.","Manage any special time requirements with the VM administrator.","hyperv",{"description": "Synchronizes the guest’s clock with its Hyper-V host."}),
  service("vmickvpexchange","Hyper-V Data Exchange Service","optional","keep","Keep if Windows runs inside a VM.","Guest and host metadata exchange stops.","Leave the guest integration configuration intact.","hyperv",{"description": "Exchanges basic configuration information between a Hyper-V guest and its host."}),
  service("vmicvss","Hyper-V Volume Shadow Copy Requestor","optional","keep","Keep for live VM backups.","Host-coordinated live backups can fail.","Review with your backup administrator.","hyperv",{"description": "Coordinates guest snapshots for backups initiated by the Hyper-V host while the VM is running."}),
  service("vmicguestinterface","Hyper-V Guest Service Interface","optional","keep","Leave at the VM’s configured default.","Host file-copy integration may fail.","If already disabled, no change is needed.","hyperv",{"description": "Lets the Hyper-V host copy files into a guest through the integration services."}),
  service("vmicvmsession","Hyper-V PowerShell Direct Service","optional","keep","Keep for host-to-guest PowerShell.","PowerShell Direct administration becomes unavailable.","Leave at the VM’s configured default.","hyperv",{"description": "Enables PowerShell Direct connections from the Hyper-V host to a Windows guest without a network connection."}),
  service("WinDefend","Microsoft Defender Antivirus Service","essential","keep","Keep malware protection available.","Microsoft Defender Antivirus cannot provide its normal scanning and malware protection.","Do not disable.","system",{"description": "Runs Microsoft Defender Antivirus scanning and malware protection."}),
  service("WdNisSvc","Microsoft Defender Antivirus Network Inspection","essential","keep","Keep Defender network inspection available.","Microsoft Defender’s network inspection for exploits is disrupted.","Do not disable.","system",{"description": "Inspects network traffic for exploits as part of Microsoft Defender Antivirus."}),
  service("MpsSvc","Windows Defender Firewall","essential","keep","Use firewall settings, not a service tweak.","Stopping the firewall service can disrupt security and Windows functionality.","Configure rules or profiles through supported firewall controls. Do not add this service to a performance script.","firewall",{"description": "Enforces Windows Firewall rules for incoming and outgoing network traffic."}),
  service("BFE","Base Filtering Engine","essential","keep","Keep network filtering available.","Firewall and IPsec functionality depend on the filtering infrastructure.","Keep it available and troubleshoot unwanted network behavior through supported settings.","firewall",{"description": "Manages the filtering infrastructure used by Windows Firewall and IPsec."}),
  service("wuauserv","Windows Update","essential","keep","Keep update servicing available.","Windows may be unable to check for, download, or install updates.","Use update settings.","system",{"description": "Enables detection, download, and installation of Windows updates."}),
  service("BITS","Background Intelligent Transfer Service","essential","keep","Keep background transfers available.","Background downloads or uploads used by Windows and dependent apps may stop or fail.","Leave the default configuration.","network",{"description": "Transfers files in the background for Windows and apps, using available network bandwidth."}),
  service("RpcSs","Remote Procedure Call (RPC)","essential","keep","Core application and service communication.","Many Windows components depend on RPC.","Keep enabled. “Remote” in the name does not mean it is optional remote access.","network",{"description": "Provides RPC support and manages COM/DCOM communication used by Windows and applications.", "bootRisk": {"reason": "Core Windows components depend on RPC. Disabling it can prevent those components from starting and disrupt startup or sign-in.", "sources": ["rpcRecovery", "system"]}}),
  service("RpcEptMapper","RPC Endpoint Mapper","essential","keep","Core RPC connection infrastructure.","Programs and services may be unable to establish RPC connections.","Keep the default configuration.","network",{"description": "Connects RPC clients with the endpoints they need.", "bootRisk": {"reason": "Core Windows components use this service to establish RPC connections. Disabling it can disrupt startup or sign-in.", "sources": ["rpcRecovery", "system"]}}),
  service("Dhcp","DHCP Client","essential","keep","Keep network address configuration available.","Address acquisition and related network registration can fail.","Do not disable it as an optimization, including on a normally stable network.","network",{"description": "Obtains IP address settings from a DHCP server and supports network address registration."}),
  service("Dnscache","DNS Client","essential","keep","Keep DNS caching and registration available.","Name-resolution behavior and dependent services can be affected.","Keep the default configuration.","network",{"description": "Caches DNS lookups and registers the computer’s name with DNS."}),
  service("DcomLaunch","DCOM Server Process Launcher","essential","keep","Core Windows component activation.","Windows components and apps that need COM/DCOM activation may fail to start.","Do not disable.","system",{"description": "Starts COM and DCOM components used by Windows and applications.", "bootRisk": {"reason": "Startup and sign-in rely on Windows components that use COM/DCOM activation. Disabling this service can prevent those components from starting.", "sources": ["system"]}}),
  service("EventLog","Windows Event Log","essential","keep","Keep diagnostic and audit records available.","Logging-dependent troubleshooting and administration can fail.","Control log retention instead of disabling the service.","network",{"description": "Records Windows events used for diagnostics, security auditing, and administration.", "bootRisk": {"condition": "When audit-failure shutdown policy is enabled", "reason": "Windows can halt if it cannot record security audits when the audit-failure shutdown policy is enabled. That policy is normally disabled.", "sources": ["audit"]}}),
  service("Schedule","Task Scheduler","essential","keep","Keep scheduled Windows work available.","Scheduled Windows maintenance and tasks created by apps or users stop running.","Do not disable.","system",{"description": "Runs scheduled tasks for Windows, installed software, and the user."}),
  service("Winmgmt","Windows Management Instrumentation","essential","keep","Keep system-management information available.","Management tools and software relying on WMI can fail.","Keep enabled, including for local management tools.","network",{"description": "Provides the WMI interface that management tools and apps use to query and manage Windows."}),
  service("CryptSvc","Cryptographic Services","essential","keep","Keep certificate and signature functions available.","Signature checks, certificate updates, and installations that depend on them can fail.","Do not disable.","system",{"description": "Supports file-signature verification and manages trusted root certificates."}),
  service("BDESVC","BitLocker Drive Encryption Service","essential","keep","Keep drive-encryption management available.","BitLocker management and automatic drive unlocking may fail. Disabling the service does not decrypt an encrypted drive.","Do not disable.","system",{"description": "Supports BitLocker drive-encryption management, unlock prompts, and automatic unlocking."}),
  service("VSS","Volume Shadow Copy","essential","keep","Keep snapshot infrastructure available.","Backups and recovery workflows using snapshots can fail.","Leave it available even when it is currently stopped.","vss",{"description": "Coordinates snapshots of volumes for backup and recovery software, including while files are in use."}),
  service("WlanSvc","WLAN AutoConfig","essential","keep","Keep Wi-Fi configuration available.","Windows may be unable to discover or connect to Wi-Fi networks.","Keep for Wi-Fi.","system",{"description": "Discovers Wi-Fi networks and manages wireless connections and profiles."}),
  service("Audiosrv","Windows Audio","essential","keep","Keep sound available.","Audio playback and recording through Windows stop working.","Do not disable.","system",{"description": "Manages Windows audio playback and recording."}),
  service("AudioEndpointBuilder","Windows Audio Endpoint Builder","essential","keep","Keep audio-device support available.","Windows may be unable to use speakers, microphones, and other audio endpoints.","Do not disable.","system",{"description": "Manages the audio endpoints that Windows uses for playback and recording devices."}),
  service("PlugPlay","Plug and Play","essential","keep","Keep hardware detection available.","Hardware detection and responses to device changes can fail or become unstable.","Do not disable.","system",{"description": "Helps Windows detect hardware and respond to device changes."}),
  service("AppXSvc","AppX Deployment Service","essential","keep","Keep packaged app deployment available.","Installation, updates, and removal of packaged apps can fail.","Leave at default.","system",{"description": "Installs, updates, and removes packaged Windows apps, including Microsoft Store apps."}),
  service("VaultSvc","Credential Manager","essential","keep","Keep credential storage available.","Apps and Windows components may be unable to retrieve saved credentials.","Do not disable.","system",{"description": "Stores and retrieves saved credentials for apps and Windows components."}),
  service("ProfSvc","User Profile Service","essential","keep","Required to load and unload user profiles.","Disabling it can prevent sign-in and sign-out.","Keep enabled so Windows can load and unload user profiles.","system",{"description": "Loads the user profile that Windows needs for a usable session.", "bootRisk": {"reason": "Microsoft explicitly warns that stopping or disabling this service can prevent users from signing in or out.", "sources": ["system"]}}),
  service("nsi","Network Store Interface Service","essential","keep","Keep Windows networking and its dependencies available.","Stopping it causes loss of network connectivity; dependent services can fail.","Keep enabled. Local and cached sign-in may still work, but sign-in that needs a domain controller may fail without a usable network.","system",{"description": "Supplies network-change notifications to Windows components.", "bootRisk": {"condition": "For sign-in that requires a live network", "reason": "Loss of networking can block domain sign-in when cached credentials are unavailable.", "sources": ["system", "cachedLogon"]}}),
  service("gpsvc","Group Policy Client","essential","keep","Keep policy processing available.","Policy application and dependent management workflows can fail.","Follow device management policy; do not disable.","network",{"description": "Applies Group Policy settings to the computer and its users."}),
];
const SERVICE_SETTINGS = {
  "DiagTrack": {
    "uri": "ms-settings:privacy-feedback",
    "path": "Settings → Privacy & security → Diagnostics & feedback",
    "action": "Turn off optional diagnostic data if you do not want to share it. Required data and other telemetry have separate controls."
  },
  "WSearch": {
    "uri": "ms-settings:search",
    "path": "Settings → Privacy & security → Search or Searching Windows",
    "action": "Reduce indexed locations or use Classic indexing. This preserves search while limiting the work it does."
  },
  "lfsvc": {
    "uri": "ms-settings:privacy-location",
    "path": "Settings → Privacy & security → Location",
    "action": "Turn off Location services or limit individual app permissions. Check whether you need Find my device first."
  },
  "DoSvc": {
    "uri": "ms-settings:delivery-optimization",
    "path": "Settings → Windows Update → Advanced options → Delivery Optimization",
    "action": "Turn off downloads from other PCs to stop peer sharing. Keep the service available for update delivery."
  },
  "CDPSvc": {
    "uri": "ms-settings:crossdevice",
    "path": "Settings → System → Nearby sharing; also review cross-device features you use",
    "action": "Turn off unused sharing features. Connected experiences have separate controls; there is no single toggle for everything this service supports."
  },
  "CDPUserSvc": {
    "uri": "ms-settings:crossdevice",
    "path": "Settings → System → Nearby sharing; also review cross-device features you use",
    "action": "Turn off the unused sharing feature. Keep the per-user service template available for other connected experiences."
  },
  "cbdhsvc": {
    "uri": "ms-settings:clipboard",
    "path": "Settings → System → Clipboard",
    "action": "Turn off Clipboard history and clipboard syncing across devices if unused. The service also supports clipboard behavior beyond these switches."
  },
  "BcastDVRUserService": {
    "uri": "ms-settings:gaming-gamedvr",
    "path": "Settings → Gaming → Captures",
    "action": "Turn off background recording if unused. You can control capture behavior without editing a per-user service template."
  },
  "BluetoothUserService": {
    "uri": "ms-settings:bluetooth",
    "path": "Settings → Bluetooth & devices",
    "action": "Turn Bluetooth off only if no keyboard, mouse, headphones, or other device needs it."
  }
};
function isScriptEligible(service) {
  return Boolean(service && service.script && !service.bootRisk && service.category !== 'essential' && service.status !== 'keep' && !service.perUser);
}
const FEATURE_GROUPS = [
  {id:'insider',icon:'monitor',title:'I’m not in the Windows Insider Program',description:'This PC runs a stable release and is not enrolled for preview builds. Regular Windows Update stays available.',services:['wisvc']},
  {id:'remote',icon:'monitor',title:'I don’t host Remote Desktop',description:'No incoming Remote Desktop sessions or device redirection. Make changes while sitting at the PC.',services:['UmRdpService','SessionEnv','TermService']},
  {id:'registry',icon:'terminal',title:'I don’t use remote registry tools',description:'No remote registry administration. Check first if this PC is managed by your employer.',services:['RemoteRegistry']},
  {id:'printing',icon:'printer',title:'I never print anything',description:'Includes physical printers, fax, shared printers, Microsoft Print to PDF, and adding or configuring printers.',services:['Fax','Spooler','PrintDeviceConfigurationService']},
  {id:'bluetooth',icon:'bluetooth',title:'I don’t use Bluetooth',description:'No Bluetooth keyboard, mouse, headphones, controller, or other peripheral.',services:['BTAGService','BthAvctpSvc','bthserv']},
  {id:'discovery',icon:'network',title:'I don’t use network discovery',description:'No automatic network device discovery, UPnP, or discoverable sharing from this PC.',services:['upnphost','SSDPSRV','fdPHost','FDResPub']},
  {id:'media',icon:'music',title:'I don’t share a media library',description:'No streaming from legacy Windows Media Player to other devices.',services:['WMPNetworkSvc']},
  {id:'fax',icon:'printer',title:'I don’t send or receive faxes',description:'The optional Windows fax feature is unused. Ordinary printing stays available.',services:['Fax']},
  {id:'retail',icon:'store',title:'This isn’t a retail demo PC',description:'No in-store Windows demonstration experience. It may already be disabled.',services:['RetailDemo']}
].map(group => ({...group, services:group.services.filter(id=>isScriptEligible(SERVICES.find(service=>service.id===id)))})).filter(group=>group.services.length);
const SCRIPT_IDS = SERVICES.filter(isScriptEligible).map(s=>s.id);
const CONSERVATIVE_PRESET = ['RemoteRegistry','Fax','RetailDemo'].filter(id=>SCRIPT_IDS.includes(id));
